### ISSUE TITLE
403 abuse-rate-limits

### ISSUE THREAD

**Issue by StefanWerW** [cantidio/node-github-pages#15]
I'm trying to run this script but i'm receiving this error from github:

`"message": "{\n  \"documentation_url\": \"https://developer.github.com/v3/#abuse-rate-limits\",\n  \"message\": \"You have triggered an abuse detection mechanism. Please wait a few minutes before you try again.\"\n}\n"`

Is that normal? btw, i'm authenticating with Personal access token

**Comment by cantidio** [comment]
Hello @StefanWerW, this is not a normal behaviour. 
Can you tell me more about how are you calling it? can you post some of the configurations that you are using?

Are you calling the script from a loop or something like that?
